DROP DATABASE portfolio;
CREATE DATABASE IF NOT EXISTS portfolio;
USE portfolio;

CREATE TABLE IF NOT EXISTS users (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
    noteId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    note JSON NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(userId)
);